jobs:
  - job: extended_test
    variables:
      - name: IMAGE_NAME
        value: ubuntu-22.04
      - name: PYTHON_VERSION
        value: 3.12
      - group: certbot-common
    strategy:
      matrix:
        farmtest-apache2:
          PYTHON_VERSION: 3.8
          TOXENV: test-farm-apache2
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - template: ../steps/tox-steps.yml
