jobs:
  - job: extended_test
    variables:
      - name: IMAGE_NAME
        value: ubuntu-22.04
      - name: PYTHON_VERSION
        value: 3.12
      - group: certbot-common
    strategy:
      matrix:
        linux-py312-integration:
          PYTHON_VERSION: 3.12
          TOXENV: integration
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - template: ../steps/tox-steps.yml
