jobs:
  - job: extended_test
    variables:
      - name: IMAGE_NAME
        value: ubuntu-18.04
      - name: PYTHON_VERSION
        value: 3.9
      - group: certbot-common
    strategy:
      matrix:
        linux-py38:
          PYTHON_VERSION: 3.8
          TOXENV: py38
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - template: ../steps/tox-steps.yml
