jobs:
  - job: extended_test
    variables:
      - name: IMAGE_NAME
        value: ubuntu-18.04
      - name: PYTHON_VERSION
        value: 3.10
      - group: certbot-common
    strategy:
      matrix:
        farmtest-sdists:
          PYTHON_VERSION: 3.7
          TOXENV: test-farm-sdists
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - template: ../steps/tox-steps.yml
