jobs:
  - job: test
    variables:
      PYTHON_VERSION: 3.11
    strategy:
      matrix:
        windows-mypy:
          IMAGE_NAME: windows-2019
          TOXENV: mypy-win
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - template: ../steps/tox-steps.yml
  - job: test_sphinx_builds
    pool:
      vmImage: ubuntu-20.04
    steps:
      - template: ../steps/sphinx-steps.yml
