jobs:
  - job: test
    variables:
      PYTHON_VERSION: 3.9
    strategy:
      matrix:
        linux-py39-lint:
          IMAGE_NAME: ubuntu-18.04
          PYTHON_VERSION: 3.6
          TOXENV: lint
        linux-py39-mypy:
          IMAGE_NAME: ubuntu-18.04
          PYTHON_VERSION: 3.6
          TOXENV: mypy
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - template: ../steps/tox-steps.yml
  - job: test_sphinx_builds
    pool:
      vmImage: ubuntu-20.04
    steps:
      - template: ../steps/sphinx-steps.yml
