jobs:
  - job: test
    variables:
      PYTHON_VERSION: 3.11
    strategy:
      matrix:
        macos-py37-cover:
          IMAGE_NAME: macOS-12
          PYTHON_VERSION: 3.7
          TOXENV: cover
        macos-cover:
          IMAGE_NAME: macOS-12
          TOXENV: cover
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - template: ../steps/tox-steps.yml
  - job: test_sphinx_builds
    pool:
      vmImage: ubuntu-20.04
    steps:
      - template: ../steps/sphinx-steps.yml
