jobs:
  - job: test
    variables:
      PYTHON_VERSION: 3.9
    strategy:
      matrix:
        macos-py36:
          IMAGE_NAME: macOS-10.15
          PYTHON_VERSION: 3.6
          TOXENV: py36
        macos-py39:
          IMAGE_NAME: macOS-10.15
          PYTHON_VERSION: 3.9
          TOXENV: py39
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - template: ../steps/tox-steps.yml
  - job: test_sphinx_builds
    pool:
      vmImage: ubuntu-20.04
    steps:
      - template: ../steps/sphinx-steps.yml
