stages:
  - stage: Deploy
    jobs:
      - template: ../jobs/snap-deploy-job.yml
      - job: publish_docker
        pool:
          vmImage: ubuntu-22.04
        strategy:
          matrix:
            amd64:
              DOCKER_ARCH: amd64
            arm32v6:
              DOCKER_ARCH: arm32v6
            arm64v8:
              DOCKER_ARCH: arm64v8
        steps:
          - bash: echo hi
            displayName: say hi
