# Nightly pipeline running each day for master.
trigger: none
pr: none
schedules:
  - cron: "30 4 * * *"
    displayName: Nightly build
    branches:
      include:
      - master
    always: true

variables:
  dockerTag: nightly
  snapBuildTimeout: 19800

stages:
  - template: templates/stages/deploy-stage.yml
    parameters:
      snapReleaseChannel: unknown
